### ISSUE TITLE
@font-face使用技巧

### ISSUE THREAD

**Issue by xiaoyann** [striverx/notes#1]
CSS3的一个模块，能做到兼容所有浏览器。
#### 用法
1. https://icomoon.io 在这个网站下载现成的，或import自己制作的svg图标转成字体。
2. css3语法 http://www.w3cplus.com/content/css3-font-face
3. 相关链接
   > http://fontawesome.io/icons/
#### 字体格式

OpenType、TrueType、Embedded OpenType（IE，微软自带）。字体文件扩展名分别为.otf、.ttf、.eot
#### 用法

``` css
// 定义一个字体
@font-face {
  font-family: myFont;
  // style: normal  italic  oblique  inherit
  font-style: italic;
  font-weight: bold;
  font-size: 22px;
  // 字体是否伸缩变形
  font-stretch: normal;
 // 字体大小写 normal  small-caps inherit
  font-variant: normal;
  // 也可以使用客户端的字体  src: local('Arial')
  src: url(myFont.otf) format('opentype')
}
// 应用到一个元素上
h1 {
  font-family: myFont;
}
```
